name: Translate Monitored Documents on Update

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml openai

      - name: Identify changed monitored files
        id: detect
        run: |
          echo "🔍 Loading translation list..."
          python .github/scripts/identify_changed_files.py > changed_files.txt
          echo "✅ Done. Changed monitored files:"
          cat changed_files.txt

      - name: Translate changed files
        run: |
          echo "⌛ Translating, please wait..."
          python .github/scripts/translate_changed_files.py changed_files.txt > translated_files.txt
          echo "✅ Done. Translated files:"
          cat translated_files.txt
        env:
          API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/docs-auto-translate
          base: main
          title: "chore(docs): auto-translate"
          commit-message: "Auto-translate updated documentation"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: |
            Automated translation for monitored docs.
            Created by GitHub Actions.
          labels: automation, docs
          delete-branch: true

      - name: Enable auto-merge (rebase)
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --rebase --auto